{
	"version": 1618485646,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/backgroud-sheet0.png",
		"images/quadro1-sheet0.png",
		"images/topo-sheet0.png",
		"images/display-sheet0.png",
		"images/barreira-sheet0.png",
		"images/carinhas-sheet0.png",
		"images/particles.png",
		"images/sprite-sheet0.png",
		"images/touch_emoc-sheet0.png",
		"images/touch_emoc-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/backgroud_menu-sheet0.png",
		"images/btn_menu_play-sheet0.png",
		"images/btn_voltar-sheet0.png",
		"images/btn_play_game-sheet0.png",
		"images/particles2.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/btn_sound-sheet0.png",
		"images/btn_sound-sheet1.png",
		"images/btn_submit-sheet0.png",
		"images/bt1-sheet0.png",
		"images/cardface1_2-sheet0.png",
		"images/cardface1_3-sheet0.png",
		"images/cardface1_4-sheet0.png",
		"images/cooltext3-sheet0.png",
		"images/cooltext-sheet0.png",
		"images/bg-sheet0.png",
		"images/btn_sound_off-sheet0.png",
		"images/btn_sound_off-sheet1.png",
		"images/sprite2sheet-sheet0.png",
		"images/btncredits-sheet0.png",
		"images/logolied-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/carinha2-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/pop.ogg",
		"media/trumpet.ogg",
		"media/bgsom.ogg",
		"media/triangulo.ogg",
		"media/theme2.ogg",
		"media/whatsapp audio 2021-04-14 at 14.48.06.ogg",
		"media/whatsapp audio 2021-04-14 at 14.39.49 (1).ogg",
		"media/whatsapp audio 2021-04-14 at 14.39.49.ogg",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}